---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rbd-csi-nodeplugin-nautilus-sa
  namespace: csi
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rbd-csi-nodeplugin-nautilus-cr
aggregationRule:
  clusterRoleSelectors:
    - matchLabels:
        rbac.rbd.csi.ceph.com/aggregate-to-rbd-csi-nodeplugin: "true"
rules: []
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rbd-csi-nodeplugin-rules-nautilus-cr
  labels:
    rbac.rbd.csi.ceph.com/aggregate-to-rbd-csi-nodeplugin: "true"
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rbd-csi-nodeplugin-nautilus-crb
subjects:
  - kind: ServiceAccount
    name: rbd-csi-nodeplugin-nautilus-sa
    namespace: csi
roleRef:
  kind: ClusterRole
  name: rbd-csi-nodeplugin-nautilus-cr
  apiGroup: rbac.authorization.k8s.io
